# Generated by Django 4.1.5 on 2023-03-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('rate', models.CharField(max_length=100)),
                ('runtime', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
            ],
        ),
    ]
