# Generated by Django 4.1.5 on 2023-03-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_moviefilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefilter',
            name='overview',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AddField(
            model_name='moviefilter',
            name='poster',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
